# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.


# The following implementation supposes that there will be one
# java_find_*.tcl present for each of the platform onto which Tcl is
# implemented.  This is currently not true, since I do not have access
# to a Mac.

global tcl_platform
package ifneeded java 1.0 [format {
    source [file join %s java.tcl] 
    source [file join %s java_find_%s.tcl]
} $dir $dir $tcl_platform(platform)]
